version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: analysis-db
    environment:
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: manufacturing
    ports:
      - '5430:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always